### ISSUE TITLE
Support for Charge 5

### ISSUE THREAD

**Issue by ticpu** [200Tigersbloxed/FitbitHRtoWS#14]
I would like to get this application working for my Charge 5 and the published application in the Fitbit application says the device is not compatible.

Where should I start to get a version of this application compatible for my model in the Fitbit gallery?

I'm able to mostly anything and run Android, Linux and Windows if needed.

**Comment by 200Tigersbloxed** [comment]
> the Fitbit application says the device is not compatible.

This is because this is a Gallery App, meaning it can only be installed on a Fitbit smartwatch, not a tracker. However, you're not out of options,

> Where should I start to get a version of this application compatible for my model in the Fitbit gallery?

I would start by using the Fitbit API. If you'd like to see an example (or wish to use this with VRChat), then I'd see this HRtoVRChat_OSC Extension that does so.

https://github.com/ButterscotchV/FitbitWebOSC

**Comment by ticpu** [comment]
I didn't make the difference between watch and tracker it seems. Thanks!
